In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\muqad\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\muqad\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\muqad\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\muqad\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\muqad\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\muqad\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\muqad\anaconda3\lib\site-packages (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\muqad\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\muqad\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\muqad\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [9]:
pd.read_excel("heart-2.xlsx")
df=pd.read_excel("heart-2.xlsx")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [10]:
# Shape of dataset
print("Dataset Shape:", df.shape)

Dataset Shape: (1025, 14)

In [11]:
# Dataset information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB
None

In [12]:
#Summary Statistics
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [15]:
# 5. Check Missing Values

missing_values = df.isna().sum()

print("Missing Values:\n")
print(missing_values)

Missing Values:

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
#Check Duplicate Rows

duplicate_rows = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 723

In [20]:
# 7. Remove Duplicate Rows

df.drop_duplicates(inplace=True)

print("New dataset shape after removing duplicates:")
print(df.shape)

New dataset shape after removing duplicates:
(302, 14)

In [22]:
# Sex mapping
df['sex'] = df['sex'].map({
    0: 'female',
    1: 'male'
})

In [23]:
# Chest Pain Type
df['cp'] = df['cp'].map({
    0: 'typical_angina',
    1: 'atypical_angina',
    2: 'non_anginal_pain',
    3: 'asymptomatic'
})

In [24]:
# Fasting Blood Sugar
df['fbs'] = df['fbs'].map({
    0: 'normal',
    1: 'high'
})

In [26]:
# Exercise Induced Angina
df['exang'] = df['exang'].map({
    0: 'no',
    1: 'yes'
})

In [28]:
# Heart Disease Target
df['target'] = df['target'].map({
    0: 'disease',
    1: 'no_disease'
})

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,NaN,typical_angina,125,212,normal,1,168,NaN,1.0,2,2,3,NaN
1,53,NaN,typical_angina,140,203,high,0,155,NaN,3.1,0,0,3,NaN
2,70,NaN,typical_angina,145,174,normal,1,125,NaN,2.6,0,0,3,NaN
3,61,NaN,typical_angina,148,203,normal,1,161,NaN,0.0,2,1,3,NaN
4,62,NaN,typical_angina,138,294,high,1,106,NaN,1.9,1,3,2,NaN

In [31]:
print("Minimum Blood Pressure:", df['trestbps'].min())
print("Minimum Cholesterol:", df['chol'].min())
print("Minimum Heart Rate:", df['thalach'].min())

Minimum Blood Pressure: 94
Minimum Cholesterol: 126
Minimum Heart Rate: 71

In [36]:
 #Separate Features and Target

target_col = 'target'

X = df.drop(columns=[target_col])

y = df[target_col]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (302, 13)
Target Shape: (302,)

In [40]:
#Save Cleaned Dataset


output_path = 'heart_cleaned.csv'

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!